### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by RACCOONX95** [Python3WebSpider/WeiboList#1]
Traceback (most recent call last):
  File "D:/test-ajax/mayunweibo.py", line 53, in <module>
    for result in results:
  File "D:/test-ajax/mayunweibo.py", line 34, in parse_page
    for item in items:
TypeError: 'NoneType' object is not iterable

找了半天，也不知道如何解决

**Comment by yslemmo** [comment]
应该是API更新了，我看了一下get到的json文件，get到数据第二个没有mblog键。
我按照新的API更新了url和get_page()方法的之后，就正常了

**Comment by ghost** [comment]
对，微博的API改了，多了几个参数

**Comment by 0xff-dev** [comment]
第一页返回的数据 cards的第二条数据不是博客信息
是关于作者的
在get_page函数中把page返回, 在parse_page中
`for index, item in enumerate(items):
    if page == 1 and index == 1:
        continue
   else:
         xxxxx
`

**Comment by YeeChe** [comment]
您好！请问最后main函数里给parse_page指定的*json函数可以替代parse_page(json, page)吗？
这个*号的具体用法是什么呢？
谢谢！

**Comment by 0xff-dev** [comment]
@YeeChe  我没太明白你说的意思，在 get_page函数中，返回的是一个tuple, parse_page增加第二个参数，是因为原来的api发生了改变，第一条是没用的数据, 所以过滤掉, 你说的*json, 你可以google "python解压赋值"

**Comment by aesdhj** [comment]
我也在看这本书，为这本书建了一个QQ群805370297，方便大家讨论

**Comment by erbangzhu** [comment]
> @YeeChe 我没太明白你说的意思，在 get_page函数中，返回的是一个tuple, parse_page增加第二个参数，是因为原来的api发生了改变，第一条是没用的数据, 所以过滤掉, 你说的*json, 你可以google "python解压赋值"

*可以保证等号前面的变量个数与等号后面的赋值个数不一致时，python不报错
