### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by Dongxuxiang1994** [Python3WebSpider/WeiboList#7]
DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
  if collection.insert(result):
Traceback (most recent call last):
  File "E:/DongXuXiang/PycharmProjects/test/ajex.py", line 59, in <module>
    for result in results:
  File "E:/DongXuXiang/PycharmProjects/test/ajex.py", line 42, in parse_page
    weibo['id'] = item.get('id')
AttributeError: 'NoneType' object has no attribute 'get'
运行的时候出错，大佬什么原因啊，小白，讲解的详细点，谢谢

**Comment by univerone** [comment]
把parse_page(json)函数里的```json.get('cards')```换成``` json.get('data').get('cards')```就行了吧，应该是ajax的文件结构有一点点变化，你看看https://m.weibo.cn/api/container/getIndex?type=uid&value=2145291155&containerid=1076032145291155&page=1
这个界面，先选取'data',再选取‘data’里面嵌套的‘cards’
```
def parse_page(json):
    if json:
        items = json.get('data').get('cards')
        for item in items:
            item = item.get('mblog')
            weibo = {}
            weibo['id'] = item.get('id')
            weibo['text'] = pq(item.get('text')).text()
            weibo['attitudes'] = item.get('attitudes_count')
            weibo['comments'] = item.get('comments_count')
            weibo['reposts'] = item.get('reposts_count')
            yield weibo
```

**Comment by Dongxuxiang1994** [comment]
明天看下，多交流


| |
dongxuxiang1994
|
|
dongxuxiang1994@163.com
|
签名由网易邮箱大师定制
在2019年1月8日 16:55，Jiang Shanshan<notifications@github.com> 写道：

把parse_page(json)函数里的json.get('cards')换成 json.get('data').get('cards')就行了吧，应该是ajax的文件结构有一点点变化，你看看https://m.weibo.cn/api/container/getIndex?type=uid&value=2145291155&containerid=1076032145291155&page=1
这个界面，先选取'data',再选取‘data’里面嵌套的‘cards’

def parse_page(json):

    if json:

        items = json.get('data').get('cards')

        for item in items:

            item = item.get('mblog')

            weibo = {}

            weibo['id'] = item.get('id')

            weibo['text'] = pq(item.get('text')).text()

            weibo['attitudes'] = item.get('attitudes_count')

            weibo['comments'] = item.get('comments_count')

            weibo['reposts'] = item.get('reposts_count')

            yield weibo

**Comment by zyy122331** [comment]
print(result),报错，好像是在爬取微博的时候有一些特殊字符，有人知道怎么解决吗

**Comment by BIanZhuo** [comment]
同问我看了下header里面的request URL和书上的requestURL不一样了，你应该只能爬取一条数据print（json）

**Comment by BIanZhuo** [comment]
同小白 求问
